### ISSUE TITLE
Potential Bug returned by the Food Spec

### ISSUE THREAD

**Issue by wms2537** [MediTrax/MediTrax#75]
```
meditrax-api  | runtime error: index out of range [1] with length 1
meditrax-api  | 
meditrax-api  | goroutine 1158 [running]:
meditrax-api  | runtime/debug.Stack()
meditrax-api  |         /usr/local/go/src/runtime/debug/stack.go:26 +0x5e
meditrax-api  | runtime/debug.PrintStack()
meditrax-api  |         /usr/local/go/src/runtime/debug/stack.go:18 +0x13
meditrax-api  | github.com/99designs/gqlgen/graphql.DefaultRecover({0x0?, 0x4749f2?}, {0xc3a3c0?, 0xc00003a0a8?})
meditrax-api  |         /go/pkg/mod/github.com/99designs/gqlgen@v0.17.55/graphql/recovery.go:17 +0x6a
meditrax-api  | github.com/99designs/gqlgen/graphql.(*OperationContext).Recover(0x437620?, {0xddff98, 0xc000587740}, {0xc3a3c0?, 0xc00003a0a8?})
meditrax-api  |         /go/pkg/mod/github.com/99designs/gqlgen@v0.17.55/graphql/context_operation.go:124 +0x38
meditrax-api  | meditrax/graph/resolvers.(*executionContext)._Query_getFoodSpecs.func1()
meditrax-api  |         /app/graph/resolvers/generated.go:14525 +0x6e
meditrax-api  | panic({0xc3a3c0?, 0xc00003a0a8?})
meditrax-api  |         /usr/local/go/src/runtime/panic.go:785 +0x132
meditrax-api  | meditrax/graph/resolvers.(*queryResolver).GetFoodSpecs(0xbbb080?, {0xddff98?, 0xc000587740?}, {0xc00049e990, 0x9})
meditrax-api  |         /app/graph/resolvers/foodspec.resolvers.go:50 +0x77c
meditrax-api  | meditrax/graph/resolvers.(*executionContext)._Query_getFoodSpecs.func2({0xddff98, 0xc000587740})
meditrax-api  |         /app/graph/resolvers/generated.go:14531 +0xca
meditrax-api  | github.com/99designs/gqlgen/graphql/executor.processExtensions.func4({0xddff98?, 0xc000587740?}, 0xc00058a460?)
meditrax-api  |         /go/pkg/mod/github.com/99designs/gqlgen@v0.17.55/graphql/executor/extensions.go:73 +0x22
meditrax-api  | meditrax/graph/resolvers.(*executionContext)._Query_getFoodSpecs(0xc0002a9280, {0xddff98, 0xc000587620}, {0xc000096480, {0xc0005875c0, 0x3, 0x3}, 0x0})
meditrax-api  |         /app/graph/resolvers/generated.go:14529 +0x20b
meditrax-api  | meditrax/graph/resolvers.(*executionContext)._Query.func19({0xddff98?, 0xc000587620?}, 0xc000678ee0?)
meditrax-api  |         /app/graph/resolvers/generated.go:23161 +0x89
meditrax-api  | meditrax/graph/resolvers.(*executionContext)._Query.func20.1({0xddff98?, 0xc000587620?})
meditrax-api  |         /app/graph/resolvers/generated.go:23167 +0x25
meditrax-api  | github.com/99designs/gqlgen/graphql/executor.processExtensions.func3({0xddff98?, 0xc000587620?}, 0x4235c0?)
meditrax-api  |         /go/pkg/mod/github.com/99designs/gqlgen@v0.17.55/graphql/executor/extensions.go:70 +0x22
meditrax-api  | meditrax/graph/resolvers.(*executionContext)._Query.func20({0xddff98, 0xc000587620})
meditrax-api  |         /app/graph/resolvers/generated.go:23166 +0xa2
meditrax-api  | meditrax/graph/resolvers.(*executionContext)._Query.func21({0x0?, 0x0?})
meditrax-api  |         /app/graph/resolvers/generated.go:23170 +0x1f
meditrax-api  | github.com/99designs/gqlgen/graphql.(*FieldSet).Dispatch(0xc0005b4050, {0xddff98?, 0xc0005875f0?})
meditrax-api  |         /go/pkg/mod/github.com/99designs/gqlgen@v0.17.55/graphql/fieldset.go:41 +0xa2
meditrax-api  | meditrax/graph/resolvers.(*executionContext)._Query(0xc0002a9280, {0xddff98, 0xc000587590}, {0xc0002a9080, 0x2, 0x2})
meditrax-api  |         /app/graph/resolvers/generated.go:23468 +0x3d13
meditrax-api  | meditrax/graph/resolvers.(*executableSchema).Exec.func1({0xddff98, 0xc000587560})
meditrax-api  |         /app/graph/resolvers/generated.go:2652 +0x230
meditrax-api  | github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1.1({0xddff98, 0xc000587560})
meditrax-api  |         /go/pkg/mod/github.com/99designs/gqlgen@v0.17.55/graphql/executor/executor.go:124 +0x25
meditrax-api  | github.com/99designs/gqlgen/graphql/executor.processExtensions.func2({0xddff98?, 0xc000587560?}, 0xb87a20?)
meditrax-api  |         /go/pkg/mod/github.com/99designs/gqlgen@v0.17.55/graphql/executor/extensions.go:67 +0x22
meditrax-api  | github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1({0xddff98, 0xc0005874a0})
meditrax-api  |         /go/pkg/mod/github.com/99designs/gqlgen@v0.17.55/graphql/executor/executor.go:123 +0x104
meditrax-api  | github.com/99designs/gqlgen/graphql/handler/transport.POST.Do({0xddff98?}, {0xddeed0, 0xc0002649a0}, 0xc00025d540, {0xddef90, 0xc000340320})
meditrax-api  |         /go/pkg/mod/github.com/99designs/gqlgen@v0.17.55/graphql/handler/transport/http_post.go:91 +0x6dd
meditrax-api  | github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP(0xc00032ab40, {0xddeed0, 0xc0002649a0}, 0xc00025d540)
meditrax-api  |         /go/pkg/mod/github.com/99designs/gqlgen@v0.17.55/graphql/handler/server.go:128 +0x225
meditrax-api  | main.main.Middleware.func2({0xddeed0, 0xc0002649a0}, 0xc00025d180)
meditrax-api  |         /app/graph/middleware/middleware.go:101 +0x5fc
meditrax-api  | net/http.HandlerFunc.ServeHTTP(0xc000264540?, {0xddeed0?, 0xc0002649a0?}, 0xc9ff08?)
meditrax-api  |         /usr/local/go/src/net/http/server.go:2220 +0x29
meditrax-api  | net/http.(*ServeMux).ServeHTTP(0xc00037e5b0?, {0xddeed0, 0xc0002649a0}, 0xc00025d180)
meditrax-api  |         /usr/local/go/src/net/http/server.go:2747 +0x1ca
meditrax-api  | main.main.(*Cors).Handler.func3({0xddeed0, 0xc0002649a0}, 0xc00025d180)
meditrax-api  |         /go/pkg/mod/github.com/rs/cors@v1.11.1/cors.go:289 +0x184
meditrax-api  | net/http.HandlerFunc.ServeHTTP(0x4107a5?, {0xddeed0?, 0xc0002649a0?}, 0xc000264901?)
meditrax-api  |         /usr/local/go/src/net/http/server.go:2220 +0x29
meditrax-api  | net/http.serverHandler.ServeHTTP({0xddbe28?}, {0xddeed0?, 0xc0002649a0?}, 0x6?)
meditrax-api  |         /usr/local/go/src/net/http/server.go:3210 +0x8e
meditrax-api  | net/http.(*conn).serve(0xc000096360, {0xddff98, 0xc00037a990})
meditrax-api  |         /usr/local/go/src/net/http/server.go:2092 +0x5d0
meditrax-api  | created by net/http.(*Server).Serve in goroutine 1
meditrax-api  |         /usr/local/go/src/net/http/server.go:3360 +0x485
```

**Comment by WangXuRa** [comment]
new bug : division by zero
